application/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// ** SUPPRESS WARNINGS IF PHP VERSION IS ABOVE 7.2 ** //

if (version_compare(PHP_VERSION, '7.2.0', '>=')) {
    error_reporting(E_ALL ^ E_NOTICE ^ E_WARNING);
}

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

// ** INIT BOOKING ** //
Route::get('/','UserBookingController@loadBooking')->name('index');

// ** AUTHORIZATION ROUTE ** //
Auth::routes();

// ** DASHBOARD ROUTE ** //
Route::get('/home', 'HomeController@index')->name('home');

// ** BOOKING AJAX REQUESTS ** //
Route::post('/get_packages', 'UserBookingController@getPackages')->name('packages');
Route::post('/get_timing_slots', 'UserBookingController@getTimingSlots')->name('slots');
Route::post('/get_update_slots', 'UserBookingController@getUpdateSlots')->name('updateSlots');
Route::post('/remove_session_addon', 'UserBookingController@removeFromList');


// ** USER ROLE ADMIN ROUTES ** //
Route::group(['middleware'=>'admin'], function(){
    Route::resource('/users','AdminUsersController');
    Route::resource('/categories', 'AdminCategoriesController');
    Route::resource('/packages', 'AdminPackagesController');
    Route::resource('/addons', 'AdminAddonsController');
    Route::resource('/settings', 'AdminSettingsController');
    Route::resource('/booking-times', 'AdminBookingTimesController');
    Route::resource('/bookings', 'AdminBookingsController');
    Route::resource('/invoices', 'AdminInvoicesController');
    Route::resource('/staff', 'AdminStaffController');
    Route::resource('/cancel-requests', 'CancelRequestController');
    Route::post('/cancel-booking/{id}', 'AdminBookingsController@cancel')->name('cancelBooking');
    Route::patch('/updateBooking/{id}', 'AdminBookingsController@update_booking_time')->name('updateBookingTime');
    // ** DATABASE UPDATE ROUTES ** //
    Route::get('/update-database', 'DatabaseUpdateController@update');
});

// ** USER ROLE CUSTOMER ROUTES ** //
Route::group(['middleware'=>'customer'], function(){
    Route::get('/customer/bookings', 'UserBookingController@index')->name('customerBookings');
    Route::get('/customer/booking/{id}', 'UserBookingController@show')->name('showBooking');
    Route::get('/customer/invoices', 'CustomerInvoiceController@index')->name('customerInvoices');
    Route::get('/customer/invoice/{id}', 'CustomerInvoiceController@show')->name('showInvoice');
    Route::get('/customer/profile', 'CustomerProfileController@index')->name('customerProfile');
    Route::patch('/customer/{id}', 'CustomerProfileController@update')->name('customerUpdate');
    Route::post('/cancel-request', 'CancelRequestController@store')->name('cancelRequest');
    Route::get('/update-booking/{id}', 'UserBookingController@update')->name('updateBooking');
    Route::patch('/booking/{id}', 'UserBookingController@update_booking')->name('postUpdateBooking');
});

// ** COMMON ROUTES FOR AUTHENTICATED USERS ** //
Route::group(['middleware'=>'authenticated'], function() {
    // ** BOOKING FORM ROUTES ** //
    Route::post('/postStep1', 'UserBookingController@postStep1')->name('postStep1');
    Route::get('/select-booking-time', 'UserBookingController@loadStep2')->name('loadStep2');
    Route::post('/postStep2', 'UserBookingController@postStep2')->name('postStep2');
    Route::get('/select-extra-services', 'UserBookingController@loadStep3')->name('loadStep3');
    Route::post('/postStep3', 'UserBookingController@postStep3')->name('postStep3');
    Route::get('/finalize-booking', 'UserBookingController@loadFinalStep')->name('loadFinalStep');
    // ** PAYMENT GATEWAYS ** //
    Route::post('/payWithStripe', 'StripeController@payWithStripe')->name('payWithStripe');
    Route::get('/payWithPaypal', 'PaypalController@payWithPaypal')->name('payWithPaypal');
    Route::get('/pay-after-service', 'OfflinePaymentController@payOffline')->name('payOffline');
    Route::get('/paymentSuccessful', 'PaypalController@paymentSuccessful')->name('paymentSuccessful');
    Route::get('/paymentFailed', 'PaypalController@paymentFailed')->name('paymentFailed');
    // ** BOOKING COMPLETE OR FAILED ROUTES ** //
    Route::get('/thank-you', 'UserBookingController@thankYou')->name('thankYou');
    Route::get('/payment-failed', 'UserBookingController@paymentFailed')->name('paymentFailed');
    // ** AUXILIARY ROUTES  ** //
    Route::resource('/session_addons','SessionAddonsController');
    Route::get('/account-disabled', function (){
        return view('errors.accountDisabled');
    })->name('accountDisabled');
    // ** PASSWORD CHANGE ROUTES ** //
    Route::get('/password/update', 'UserPasswordController@index')->name('changePassword');
    Route::patch('/password/update/{id}', 'UserPasswordController@update')->name('postChangePassword');
});

application/app/CancelRequest.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CancelRequest extends Model
{
    protected $guarded = [];

    public function booking()
    {
        return $this->belongsTo(Booking::class);
    }
}

application/app/Http/Controllers/CancelRequestController.php
<?php

namespace App\Http\Controllers;

use App\Booking;
use App\CancelRequest;
use App\Mail\AdminCancellationNotification;
use App\Mail\CancellationReceived;
use App\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Session;

class CancelRequestController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Cancel Requests Controller
    |--------------------------------------------------------------------------
    |
    | This controller let customers request a cancellation and allow admin
    | to update or delete a cancel request.
    |
    */

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cancel_requests = CancelRequest::all();
        return view('cancel_requests.index', compact('cancel_requests'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();

        $input['status'] = __('backend.pending');
        CancelRequest::create($input);

        $booking = Booking::find($input['booking_id']);
        $admin = Role::find(1)->users()->get();

        try {
            Mail::to($request->user())->send(new CancellationReceived($booking));
            foreach($admin as $recipient)
            {
                Mail::to($recipient)->send(new AdminCancellationNotification($booking , $recipient));
            }
        } catch(\Exception $ex) {
            //do nothing
        }

        //set session message and redirect back to showBooking
        Session::flash('cancel_request_received', __('backend.cancel_request_received'));
        return redirect()->route('showBooking', $input['booking_id']);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->all();

        $cancel_request = CancelRequest::find($id);
        $cancel_request->update($input);

        //set session message and redirect back to cancel-requests.index
        Session::flash('cancel_request_updated', __('backend.cancel_request_updated'));
        return redirect()->route('cancel-requests.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cancel_request = CancelRequest::find($id);
        $cancel_request->delete();

        //set session message and redirect back to cancel-requests.index
        Session::flash('cancel_request_deleted', __('backend.cancel_request_deleted'));
        return redirect()->route('cancel-requests.index');
    }

}

application/resources/views/cancel_requests/index.blade.php
@extends('layouts.admin', ['title' => __('backend.cancel_request_admin_menu')])

@section('content')

    <div class="page-title">
        <h3>{{ __('backend.admin_cancel_title') }}</h3>
        <div class="page-breadcrumb">
            <ol class="breadcrumb">
                <li><a href="{{ route('home') }}">{{ __('backend.home') }}</a></li>
                <li class="active">{{ __('backend.cancel_request_admin_menu') }}</li>
            </ol>
        </div>
    </div>

    <div id="main-wrapper">
        <div class="row">
            <div class="col-md-12">
                @include('alerts.cancelRequest')
                <div class="panel panel-white">
                    <div class="panel-heading clearfix">
                        <h4 class="panel-title">{{ __('backend.admin_cancel_title') }}</h4>
                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table id="xtreme-table" class="display table" style="width: 100%; cellspacing: 0;">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>{{ __('backend.booking') }} #</th>
                                    <th>{{ __('backend.reason') }}</th>
                                    <th>{{ __('backend.status') }}</th>
                                    <th>{{ __('backend.created') }}</th>
                                    <th>{{ __('backend.updated') }}</th>
                                    <th>{{ __('backend.actions') }}</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>#</th>
                                    <th>{{ __('backend.booking') }} #</th>
                                    <th>{{ __('backend.reason') }}</th>
                                    <th>{{ __('backend.status') }}</th>
                                    <th>{{ __('backend.created') }}</th>
                                    <th>{{ __('backend.updated') }}</th>
                                    <th>{{ __('backend.actions') }}</th>
                                </tr>
                                </tfoot>
                                <tbody>
                                @foreach($cancel_requests as $cancel_request)
                                    <tr>
                                        <td>{{ $cancel_request->id }}</td>
                                        <td>{{ $cancel_request->booking->id }}</td>
                                        <td>{{ $cancel_request->reason }}</td>
                                        <td><span class="label {{ $cancel_request->status == __('backend.pending') ? 'label-danger' : 'label-success' }}">{{ $cancel_request->status }}</span></td>
                                        <td>{{ $cancel_request->created_at->diffForHumans() }}</td>
                                        <td>{{ $cancel_request->updated_at->diffForHumans() }}</td>
                                        <td>
                                            <a href="{{ route('bookings.show', $cancel_request->booking->id) }}" class="btn btn-primary btn-sm">{{ __('backend.view_booking') }}</a>
                                            <a href="{{ route('invoices.show', $cancel_request->booking->invoice->id) }}" class="btn btn-info btn-sm">{{ __('backend.view_invoice') }}</a>
                                            @if($cancel_request->status != __('backend.completed'))
                                                <a class="btn btn-success btn-sm" data-toggle="modal" data-target="#update_req{{ $cancel_request->id }}">{{ __('backend.update') }}</a>
                                            @endif
                                            <a href="" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#delete_req{{ $cancel_request->id }}">{{ __('backend.delete_btn') }}</a>
                                        </td>
                                    </tr>
                                    <div class="modal fade" id="update_req{{ $cancel_request->id }}" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-keyboard="false">
                                        <div class="modal-dialog">
                                            <form method="post" action="{{ route('cancel-requests.update', $cancel_request->id) }}">
                                                @csrf
                                                {{ method_field('PATCH') }}
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                        <h4 class="modal-title" id="myModalLabel">{{ __('backend.update') }}</h4>
                                                    </div>
                                                    <div class="modal-body">
                                                        <div class="form-group">
                                                            <label>{{ __('backend.status') }}</label>
                                                            <select class="form-control" name="status" required>
                                                                <option {{ $cancel_request->status == __('backend.pending') ? 'selected' : '' }}>{{ __('backend.pending') }}</option>
                                                                <option {{ $cancel_request->status == __('backend.rejected') ? 'selected' : '' }}>{{ __('backend.rejected') }}</option>
                                                            </select>
                                                        </div>
                                                        <div class="form-group">
                                                            <label>{{ __('backend.reason_for_cancellation') }}</label>
                                                            <textarea class="form-control" name="reason" required>{{ $cancel_request->reason }}</textarea>
                                                        </div>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="submit" class="btn btn-success">{{ __('backend.update') }}</button>
                                                        <button type="button" class="btn btn-danger" data-dismiss="modal">{{ __('backend.close') }}</button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                    <div id="delete_req{{ $cancel_request->id }}" class="modal fade" role="dialog" data-keyboard="false" data-backdrop="static">
                                        <div class="modal-dialog">
                                            <!-- Modal content-->
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                    <h4 class="modal-title">{{ __('backend.confirm') }}</h4>
                                                </div>
                                                <div class="modal-body">
                                                    <p>{{ __('backend.delete_cancel_request_message') }}</p>
                                                </div>
                                                <form method="post" action="{{ route('cancel-requests.destroy', $cancel_request->id) }}">
                                                    <div class="modal-footer">
                                                        {{csrf_field()}}
                                                        {{ method_field('DELETE') }}
                                                        <button type="submit" class="btn btn-danger">{{ __('backend.delete_btn') }}</button>
                                                        <button type="button" class="btn btn-primary" data-dismiss="modal">{{ __('backend.no') }}</button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection