application/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// ** SUPPRESS WARNINGS IF PHP VERSION IS ABOVE 7.2 ** //

if (version_compare(PHP_VERSION, '7.2.0', '>=')) {
    error_reporting(E_ALL ^ E_NOTICE ^ E_WARNING);
}

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

// ** INIT BOOKING ** //
Route::get('/','UserBookingController@loadBooking')->name('index');

// ** AUTHORIZATION ROUTE ** //
Auth::routes();

// ** DASHBOARD ROUTE ** //
Route::get('/home', 'HomeController@index')->name('home');

// ** BOOKING AJAX REQUESTS ** //
Route::post('/get_packages', 'UserBookingController@getPackages')->name('packages');
Route::post('/get_timing_slots', 'UserBookingController@getTimingSlots')->name('slots');
Route::post('/get_update_slots', 'UserBookingController@getUpdateSlots')->name('updateSlots');
Route::post('/remove_session_addon', 'UserBookingController@removeFromList');


// ** USER ROLE ADMIN ROUTES ** //
Route::group(['middleware'=>'admin'], function(){
    Route::resource('/users','AdminUsersController');
    Route::resource('/categories', 'AdminCategoriesController');
    Route::resource('/packages', 'AdminPackagesController');
    Route::resource('/addons', 'AdminAddonsController');
    Route::resource('/settings', 'AdminSettingsController');
    Route::resource('/booking-times', 'AdminBookingTimesController');
    Route::resource('/bookings', 'AdminBookingsController');
    Route::resource('/invoices', 'AdminInvoicesController');
    Route::resource('/staff', 'AdminStaffController');
    Route::resource('/cancel-requests', 'CancelRequestController');
    Route::post('/cancel-booking/{id}', 'AdminBookingsController@cancel')->name('cancelBooking');
    Route::patch('/updateBooking/{id}', 'AdminBookingsController@update_booking_time')->name('updateBookingTime');
    // ** DATABASE UPDATE ROUTES ** //
    Route::get('/update-database', 'DatabaseUpdateController@update');
});

// ** USER ROLE CUSTOMER ROUTES ** //
Route::group(['middleware'=>'customer'], function(){
    Route::get('/customer/bookings', 'UserBookingController@index')->name('customerBookings');
    Route::get('/customer/booking/{id}', 'UserBookingController@show')->name('showBooking');
    Route::get('/customer/invoices', 'CustomerInvoiceController@index')->name('customerInvoices');
    Route::get('/customer/invoice/{id}', 'CustomerInvoiceController@show')->name('showInvoice');
    Route::get('/customer/profile', 'CustomerProfileController@index')->name('customerProfile');
    Route::patch('/customer/{id}', 'CustomerProfileController@update')->name('customerUpdate');
    Route::post('/cancel-request', 'CancelRequestController@store')->name('cancelRequest');
    Route::get('/update-booking/{id}', 'UserBookingController@update')->name('updateBooking');
    Route::patch('/booking/{id}', 'UserBookingController@update_booking')->name('postUpdateBooking');
});

// ** COMMON ROUTES FOR AUTHENTICATED USERS ** //
Route::group(['middleware'=>'authenticated'], function() {
    // ** BOOKING FORM ROUTES ** //
    Route::post('/postStep1', 'UserBookingController@postStep1')->name('postStep1');
    Route::get('/select-booking-time', 'UserBookingController@loadStep2')->name('loadStep2');
    Route::post('/postStep2', 'UserBookingController@postStep2')->name('postStep2');
    Route::get('/select-extra-services', 'UserBookingController@loadStep3')->name('loadStep3');
    Route::post('/postStep3', 'UserBookingController@postStep3')->name('postStep3');
    Route::get('/finalize-booking', 'UserBookingController@loadFinalStep')->name('loadFinalStep');
    // ** PAYMENT GATEWAYS ** //
    Route::post('/payWithStripe', 'StripeController@payWithStripe')->name('payWithStripe');
    Route::get('/payWithPaypal', 'PaypalController@payWithPaypal')->name('payWithPaypal');
    Route::get('/pay-after-service', 'OfflinePaymentController@payOffline')->name('payOffline');
    Route::get('/paymentSuccessful', 'PaypalController@paymentSuccessful')->name('paymentSuccessful');
    Route::get('/paymentFailed', 'PaypalController@paymentFailed')->name('paymentFailed');
    // ** BOOKING COMPLETE OR FAILED ROUTES ** //
    Route::get('/thank-you', 'UserBookingController@thankYou')->name('thankYou');
    Route::get('/payment-failed', 'UserBookingController@paymentFailed')->name('paymentFailed');
    // ** AUXILIARY ROUTES  ** //
    Route::resource('/session_addons','SessionAddonsController');
    Route::get('/account-disabled', function (){
        return view('errors.accountDisabled');
    })->name('accountDisabled');
    // ** PASSWORD CHANGE ROUTES ** //
    Route::get('/password/update', 'UserPasswordController@index')->name('changePassword');
    Route::patch('/password/update/{id}', 'UserPasswordController@update')->name('postChangePassword');
});

application/app/Booking.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Booking extends Model
{
    protected $guarded = [];

    public function invoice()
    {
        return $this->hasOne(Invoice::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function package()
    {
        return $this->belongsTo(Package::class);
    }

    public function addons()
    {
        return $this->belongsToMany(Addon::class)->withTimestamps();
    }

    public function cancel_request()
    {
        return $this->hasOne(CancelRequest::class);
    }

    public function staff()
    {
        return $this->belongsTo(StaffMember::class, 'staff_member_id');
    }
}

application/resources/views/bookings/edit.blade.php
@extends('layouts.admin', ['title' => __('backend.update_booking')])


@section('styles')

    <link rel="stylesheet" href="{{ asset('plugins/datepicker/css/bootstrap-datepicker.min.css') }}">

@endsection

@section('content')

    <div class="page-title">
        <h3>{{ __('backend.update_booking') }} # {{ $booking->id }}</h3>
        <div class="page-breadcrumb">
            <ol class="breadcrumb">
                <li><a href="{{ route('home') }}">{{ __('backend.home') }}</a></li>
                <li><a href="{{ route('bookings.index') }}">{{ __('backend.bookings') }}</a></li>
                <li class="active">{{ __('backend.update_booking') }}</li>
            </ol>
        </div>
    </div>

    <div id="main-wrapper">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-white">
                    <div class="panel-heading clearfix">
                        <h4 class="panel-title">{{ __('backend.change_booking_time') }}</h4>
                    </div>
                    <div class="panel-body">
                        <br>
                        <form method="post" id="update_booking_time" action="{{ route('updateBookingTime', $booking->id) }}">
                            {{ csrf_field() }}
                            {{ method_field('PATCH') }}
                            <div class="alert alert-info">
                                {{ __('backend.current_booking_time', ['date' => $booking->booking_date, 'time' => $booking->booking_time]) }}
                            </div>
                            <input type="hidden" name="booking_id" id="booking_id" value="{{ $booking->id }}">
                            <div class="form-group">
                                <label><strong>{{ __('app.select_date') }}</strong></label>
                                <input type="text" class="form-control" name="event_date_bk"
                                       id="event_date_bk" placeholder="{{ __('app.date_placeholder') }}">
                                <p class="text-danger hidden" id="date_error_holder_bk">
                                    {{ __('app.date_error') }}
                                </p>
                            </div>
                            <div class="col-md-12">
                                <div id="slots_loader" class="hidden"><p style="text-align: center;"><img src="{{ asset('images/loader.gif') }}" width="52" height="52"></p></div>
                            </div>
                            <div class="col-md-12">
                                <div id="slots_holder"></div>
                            </div>
                            <div class="alert alert-danger col-md-12 hidden" id="slot_error">
                                {{ __('app.time_slot_error') }}
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary btn-lg btn-block">{{ __('backend.change_booking_time') }}</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('scripts')


    <script src="{{ asset('plugins/datepicker/js/bootstrap-datepicker.min.js') }}"></script>
    @if(App::getLocale()=="es")
        <script src="{{ asset('plugins/datepicker/locales/bootstrap-datepicker.es.min.js') }}"></script>
    @elseif(App::getLocale()=="fr")
        <script src="{{ asset('plugins/datepicker/locales/bootstrap-datepicker.fr.min.js') }}"></script>
    @elseif(App::getLocale()=="de")
        <script src="{{ asset('plugins/datepicker/locales/bootstrap-datepicker.de.min.js') }}"></script>
    @elseif(App::getLocale()=="da")
        <script src="{{ asset('plugins/datepicker/locales/bootstrap-datepicker.da.min.js') }}"></script>
    @elseif(App::getLocale()=="it")
        <script src="{{ asset('plugins/datepicker/locales/bootstrap-datepicker.it.min.js') }}"></script>
    @elseif(App::getLocale()=="pt")
        <script src="{{ asset('plugins/datepicker/locales/bootstrap-datepicker.pt.min.js') }}"></script>
    @endif

    <script>
        var nowDate = new Date();
        var today = new Date(nowDate.getFullYear(), nowDate.getMonth(), nowDate.getDate(), 0, 0, 0, 0);

        $('#event_date_bk').datepicker({
            autoclose: true,
            orientation : 'bottom left',
            startDate: today,
            format: 'dd-mm-yyyy',
            daysOfWeekDisabled: "{{ $disable_days_string }}",
            language: "{{ App::getLocale() }}"
        });

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $('input[id="event_date_bk"]').change(function () {
            //populate timing slots
            var selected_date;
            var booking_id;
            selected_date = $(this).val();
            booking_id = $('input[id="booking_id"]').val();

            //prepare to send ajax request
            $.ajax({
                type: 'POST',
                url: '{{ route('index') }}/get_update_slots',
                data: {event_date:selected_date , booking:booking_id},
                beforeSend: function() {
                    $('#slots_loader').removeClass('hidden');
                },
                success: function(response) {
                    $('#slots_holder').html(response);
                },
                complete: function () {
                    $('#slots_loader').addClass('hidden');
                }
            });
        });

        $('#slots_holder').on('click', 'a.btn-slot', function() {
            var slot_time = $(this).attr('data-slot-time');
            $('#slots_holder').find('.btn-slot').removeClass('btn-info').addClass('btn-default');
            $('#booking_slot').remove();
            $('#update_booking_time').append('<input type="hidden" name="booking_slot" id="booking_slot" value="'+slot_time+'">');
            $(this).removeClass('btn-default').addClass('btn-info');
        });


        $('#update_booking_time').submit(function(e){

            var check = true;
            var event_date;
            event_date = $('input[name=event_date_bk]').val();
            var booking_slot;
            booking_slot = $('input[name=booking_slot]').val();

            if(event_date === "")
            {
                $('#date_error_holder_bk').removeClass('hidden');
                check = false;
            }

            if(check === false)
            {
                return false;
            }
            else if(check === true)
            {
                if(booking_slot === undefined)
                {
                    $('#slot_error').removeClass('hidden');
                    return false;
                }
                else
                {
                    e.submit();
                }
            }
        });

    </script>

@endsection

application/resources/views/bookings/index.blade.php
@extends('layouts.admin', ['title' => __('backend.bookings')])

@section('content')

    <div class="page-title">
        <h3>{{ __('backend.bookings') }}</h3>
        <div class="page-breadcrumb">
            <ol class="breadcrumb">
                <li><a href="{{ route('home') }}">{{ __('backend.home') }}</a></li>
                <li class="active">{{ __('backend.bookings') }}</li>
            </ol>
        </div>
    </div>

    <div id="main-wrapper">
        <div class="row">
            <div class="col-md-12">
                @include('alerts.bookings')
                <div class="panel panel-white">
                    <div class="panel-heading clearfix">
                        <h4 class="panel-title">{{ __('backend.bookings') }}</h4>
                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table id="xtreme-table" class="display table" style="width: 100%; cellspacing: 0;">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>{{ __('backend.category') }}</th>
                                    <th>{{ __('backend.assigned') }}</th>
                                    <th>{{ __('backend.package') }}</th>
                                    <th>{{ __('backend.date') }}</th>
                                    <th>{{ __('backend.time') }}</th>
                                    <th>{{ __('backend.status') }}</th>
                                    <th>{{ __('backend.created') }}</th>
                                    <th>{{ __('backend.actions') }}</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>#</th>
                                    <th>{{ __('backend.category') }}</th>
                                    <th>{{ __('backend.assigned') }}</th>
                                    <th>{{ __('backend.package') }}</th>
                                    <th>{{ __('backend.date') }}</th>
                                    <th>{{ __('backend.time') }}</th>
                                    <th>{{ __('backend.status') }}</th>
                                    <th>{{ __('backend.created') }}</th>
                                    <th>{{ __('backend.actions') }}</th>
                                </tr>
                                </tfoot>
                                <tbody>
                                @foreach($bookings as $booking)
                                    <tr>
                                        <td>{{ $booking->id }}</td>
                                        <td>{{ $booking->package->category->title }}</td>
                                        <td>{{ $booking->staff->first_name }} {{ $booking->staff->last_name }}</td>
                                        <td>{{ $booking->package->title }}</td>
                                        <td>{{ $booking->booking_date }}</td>
                                        <td>{{ $booking->booking_time }}</td>
                                        <td><span class="label {{ $booking->status == __('backend.cancelled') ? 'label-danger' : 'label-success' }}">{{ $booking->status }}</span></td>
                                        <td>{{ $booking->created_at->diffForHumans() }}</td>
                                        <td>
                                            <a href="{{ route('bookings.show', $booking->id) }}" class="btn btn-primary btn-sm">{{ __('backend.details') }}</a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection